### PR TITLE
Add Laravel 10

### PR DESCRIPTION
**Pull request by maddhatter**
Add Laravel 10.x to `composer.json` and the README

### CODE REVIEW

**Comment by guilhermegonzaga** [comment]
@maddhatter

It's been a few years since I've messed with PHP, but I think it's worth keeping this module active for the community.

Could you check why the tests didn't pass and resolve it to ensure it will work correctly?

Thank you for your support.

**Comment by maddhatter** [comment]
@guilhermegonzaga it looks like the unit tests have been failing for a while, and weren't introduced w/ this PR.

I found a comment here with a more detailed reason than I can hope to create: https://github.com/guilhermegonzaga/presenter/pull/12#issuecomment-1036281387

**Comment by pacoorozco** [comment]
@guilhermegonzaga As I pointed out previously, the GH workflow should be updated to pass the test with all the supported PHP versions.

This is what you should change: #13 

I can create a new PR to fix the unit tests if you want.

**Comment by guilhermegonzaga** [comment]
Thanks for the information @pacoorozco and @maddhatter 

I've merged and released the new version, I'll take some time soon to sort out the testing issue.

**Pull request merged**
